# Generated by Django 5.0 on 2024-01-07 06:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=8)),
                ('players_connected', models.IntegerField(default=0)),
                ('dealer', models.IntegerField(default=0)),
                ('current_player', models.IntegerField(default=0)),
                ('big_blind_player', models.IntegerField(default=0)),
                ('small_blind_player', models.IntegerField(default=0)),
                ('starting_chips', models.IntegerField(default=1000)),
                ('small_blind', models.IntegerField(default=25)),
                ('big_blind', models.IntegerField(default=50)),
                ('last_raise', models.IntegerField(default=0)),
                ('biggest_bet', models.IntegerField(default=0)),
                ('rounds_played', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('all_played', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('round_ended', models.BooleanField(default=False)),
                ('game_initialized', models.BooleanField(default=False)),
                ('game_in_progress', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=30)),
                ('name', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('chips', models.IntegerField(default=1000)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_action', models.CharField(blank=True, max_length=20)),
                ('last_raise', models.IntegerField(default=0)),
                ('in_game_order', models.IntegerField(default=0)),
                ('chips', models.IntegerField(default=0)),
                ('highest_combination', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('round_bet', models.IntegerField(default=0)),
                ('is_in_game', models.BooleanField(default=False)),
                ('can_check', models.BooleanField(default=False)),
                ('can_raise', models.BooleanField(default=False)),
                ('can_call', models.BooleanField(default=False)),
                ('is_folded', models.BooleanField(default=False)),
                ('is_all_in', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('value', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=20)),
                ('location', models.CharField(default='DECK', max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_app.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poker_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('is_game_started', models.BooleanField(default=False)),
                ('invitations', models.ManyToManyField(blank=True, related_name='room_invitations', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
