# Generated by Django 5.0 on 2024-01-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0004_alter_room_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
    ]
