# Generated by Django 5.0 on 2024-01-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0007_alter_room_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
