# Generated by Django 5.0 on 2024-01-03 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0011_remove_room_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invitations',
            field=models.ManyToManyField(blank=True, related_name='room_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
