# Generated by Django 5.0 on 2024-01-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_game_started', models.BooleanField(default=False)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('starting_chips', models.IntegerField(default=1000)),
                ('big_blind_value', models.IntegerField(default=0)),
            ],
        ),
    ]
