# Generated by Django 5.0.1 on 2024-01-12 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('is_started', models.BooleanField(default=False)),
                ('round_status', models.CharField(max_length=255)),
                ('summary_pot', models.IntegerField(default=0)),
                ('starting_chips', models.IntegerField(default=1000)),
                ('big_blind_value', models.IntegerField(default=0)),
                ('small_blind_value', models.IntegerField(default=0)),
                ('current_player_move', models.IntegerField(default=0)),
                ('dealer_index', models.IntegerField(default=0)),
                ('small_blind_player', models.IntegerField(default=0)),
                ('big_blind_player', models.IntegerField(default=0)),
                ('total_players_count', models.IntegerField(default=0)),
                ('round_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_in_game', models.IntegerField(default=1000)),
                ('personal_pot_in_round', models.IntegerField(default=0)),
                ('highest_combination', models.CharField(max_length=255)),
                ('is_playing_status', models.BooleanField(default=0)),
                ('index_in_table', models.IntegerField(default=0)),
                ('all_in_status', models.BooleanField(default=False)),
                ('can_check_status', models.BooleanField(default=False)),
                ('can_raise_status', models.BooleanField(default=False)),
                ('is_small_blind', models.BooleanField(default=False)),
                ('is_big_blind', models.BooleanField(default=False)),
                ('is_dealer', models.BooleanField(default=False)),
                ('round_number', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
